#############################################################################
# Makefile for building: Qt-GUI
# Generated by qmake (2.01a) (Qt 4.8.3) on: Sun Apr 14 11:21:57 2013
# Project:  Qt-GUI.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Qt-GUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = account.cpp \
		common.cpp \
		connector.cpp \
		create_account.cpp \
		dialog.cpp \
		entry.cpp \
		favorite.cpp \
		main.cpp \
		mainwindow.cpp \
		movies.cpp \
		result.cpp \
		series.cpp \
		sign_out.cpp \
		whats_new.cpp moc_account.cpp \
		moc_create_account.cpp \
		moc_dialog.cpp \
		moc_entry.cpp \
		moc_favorite.cpp \
		moc_mainwindow.cpp \
		moc_movies.cpp \
		moc_result.cpp \
		moc_series.cpp \
		moc_sign_out.cpp \
		moc_whats_new.cpp \
		qrc_application.cpp
OBJECTS       = account.o \
		common.o \
		connector.o \
		create_account.o \
		dialog.o \
		entry.o \
		favorite.o \
		main.o \
		mainwindow.o \
		movies.o \
		result.o \
		series.o \
		sign_out.o \
		whats_new.o \
		moc_account.o \
		moc_create_account.o \
		moc_dialog.o \
		moc_entry.o \
		moc_favorite.o \
		moc_mainwindow.o \
		moc_movies.o \
		moc_result.o \
		moc_series.o \
		moc_sign_out.o \
		moc_whats_new.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Qt-GUI.pro
QMAKE_TARGET  = Qt-GUI
DESTDIR       = 
TARGET        = Qt-GUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qt-GUI.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Qt-GUI.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Qt-GUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Qt-GUI1.0.0 || $(MKDIR) .tmp/Qt-GUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qt-GUI1.0.0/ && $(COPY_FILE) --parents account.h common.h connector.h create_account.h dialog.h entry.h favorite.h mainwindow.h movies.h result.h series.h sign_out.h whats_new.h .tmp/Qt-GUI1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/Qt-GUI1.0.0/ && $(COPY_FILE) --parents account.cpp common.cpp connector.cpp create_account.cpp dialog.cpp entry.cpp favorite.cpp main.cpp mainwindow.cpp movies.cpp result.cpp series.cpp sign_out.cpp whats_new.cpp .tmp/Qt-GUI1.0.0/ && (cd `dirname .tmp/Qt-GUI1.0.0` && $(TAR) Qt-GUI1.0.0.tar Qt-GUI1.0.0 && $(COMPRESS) Qt-GUI1.0.0.tar) && $(MOVE) `dirname .tmp/Qt-GUI1.0.0`/Qt-GUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qt-GUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_account.cpp moc_create_account.cpp moc_dialog.cpp moc_entry.cpp moc_favorite.cpp moc_mainwindow.cpp moc_movies.cpp moc_result.cpp moc_series.cpp moc_sign_out.cpp moc_whats_new.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_account.cpp moc_create_account.cpp moc_dialog.cpp moc_entry.cpp moc_favorite.cpp moc_mainwindow.cpp moc_movies.cpp moc_result.cpp moc_series.cpp moc_sign_out.cpp moc_whats_new.cpp
moc_account.cpp: sign_out.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		account.h \
		whats_new.h \
		common.h \
		series.h \
		account.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) account.h -o moc_account.cpp

moc_create_account.cpp: connector.h \
		dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h \
		create_account.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) create_account.h -o moc_create_account.cpp

moc_dialog.cpp: dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_entry.cpp: entry.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) entry.h -o moc_entry.cpp

moc_favorite.cpp: result.h \
		connector.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		favorite.h \
		common.h \
		whats_new.h \
		series.h \
		favorite.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) favorite.h -o moc_favorite.cpp

moc_mainwindow.cpp: movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		whats_new.h \
		common.h \
		series.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_movies.cpp: movies.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) movies.h -o moc_movies.cpp

moc_result.cpp: result.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) result.h -o moc_result.cpp

moc_series.cpp: series.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) series.h -o moc_series.cpp

moc_sign_out.cpp: sign_out.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sign_out.h -o moc_sign_out.cpp

moc_whats_new.cpp: result.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		favorite.h \
		connector.h \
		common.h \
		whats_new.h \
		series.h \
		whats_new.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) whats_new.h -o moc_whats_new.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		logo2.png \
		logo.png \
		back_home.png \
		movies_logo.png \
		images/007.png \
		images/logo.png \
		images/009.png \
		images/copy.png \
		images/10.png \
		images/background.jpeg \
		images/green.jpeg \
		images/11.png \
		images/12.png \
		images/wood.png \
		images/images.jpeg \
		images/17.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

account.o: account.cpp account.h \
		sign_out.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o account.o account.cpp

common.o: common.cpp common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

connector.o: connector.cpp connector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connector.o connector.cpp

create_account.o: create_account.cpp create_account.h \
		connector.h \
		dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o create_account.o create_account.cpp

dialog.o: dialog.cpp dialog.h \
		create_account.h \
		connector.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

entry.o: entry.cpp entry.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entry.o entry.cpp

favorite.o: favorite.cpp favorite.h \
		result.h \
		connector.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o favorite.o favorite.cpp

main.o: main.cpp dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

movies.o: movies.cpp movies.h \
		favorite.h \
		result.h \
		connector.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		dialog.h \
		entry.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movies.o movies.cpp

result.o: result.cpp result.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result.o result.cpp

series.o: series.cpp series.h \
		favorite.h \
		result.h \
		connector.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		whats_new.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o series.o series.cpp

sign_out.o: sign_out.cpp sign_out.h \
		dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		account.h \
		whats_new.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sign_out.o sign_out.cpp

whats_new.o: whats_new.cpp whats_new.h \
		result.h \
		sign_out.h \
		account.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		favorite.h \
		connector.h \
		common.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whats_new.o whats_new.cpp

moc_account.o: moc_account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_account.o moc_account.cpp

moc_create_account.o: moc_create_account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_create_account.o moc_create_account.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_entry.o: moc_entry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_entry.o moc_entry.cpp

moc_favorite.o: moc_favorite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_favorite.o moc_favorite.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_movies.o: moc_movies.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_movies.o moc_movies.cpp

moc_result.o: moc_result.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_result.o moc_result.cpp

moc_series.o: moc_series.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_series.o moc_series.cpp

moc_sign_out.o: moc_sign_out.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sign_out.o moc_sign_out.cpp

moc_whats_new.o: moc_whats_new.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whats_new.o moc_whats_new.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

