#############################################################################
# Makefile for building: finalproject.app/Contents/MacOS/finalproject
# Generated by qmake (2.01a) (Qt 4.8.4) on: Fri Apr 12 16:01:13 2013
# Project:  finalproject.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile finalproject.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang -I. -I/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/include -I. -I. -F/usr/local/Cellar/qt/4.8.4/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.4/lib -L/usr/local/Cellar/qt/4.8.4/lib -framework QtGui -L/usr/local/Cellar/qt/4.8.4/lib -F/usr/local/Cellar/qt/4.8.4/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = account.cpp \
		common.cpp \
		connector.cpp \
		create_account.cpp \
		dialog.cpp \
		entry.cpp \
		favorite.cpp \
		main.cpp \
		mainwindow.cpp \
		movies.cpp \
		result.cpp \
		series.cpp \
		sign_out.cpp \
		whats_new.cpp moc_account.cpp \
		moc_create_account.cpp \
		moc_dialog.cpp \
		moc_entry.cpp \
		moc_favorite.cpp \
		moc_mainwindow.cpp \
		moc_movies.cpp \
		moc_result.cpp \
		moc_series.cpp \
		moc_sign_out.cpp \
		moc_whats_new.cpp \
		qrc_application.cpp
OBJECTS       = account.o \
		common.o \
		connector.o \
		create_account.o \
		dialog.o \
		entry.o \
		favorite.o \
		main.o \
		mainwindow.o \
		movies.o \
		result.o \
		series.o \
		sign_out.o \
		whats_new.o \
		moc_account.o \
		moc_create_account.o \
		moc_dialog.o \
		moc_entry.o \
		moc_favorite.o \
		moc_mainwindow.o \
		moc_movies.o \
		moc_result.o \
		moc_series.o \
		moc_sign_out.o \
		moc_whats_new.o \
		qrc_application.o
DIST          = /usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf \
		finalproject.pro
QMAKE_TARGET  = finalproject
DESTDIR       = 
TARGET        = finalproject.app/Contents/MacOS/finalproject

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile finalproject.app/Contents/PkgInfo finalproject.app/Contents/Resources/empty.lproj finalproject.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) finalproject.app/Contents/MacOS/ || $(MKDIR) finalproject.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: finalproject.pro  /usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile finalproject.pro
/usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.4/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile finalproject.pro

finalproject.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) finalproject.app/Contents || $(MKDIR) finalproject.app/Contents 
	@$(DEL_FILE) finalproject.app/Contents/PkgInfo
	@echo "APPL????" >finalproject.app/Contents/PkgInfo
finalproject.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) finalproject.app/Contents/Resources || $(MKDIR) finalproject.app/Contents/Resources 
	@touch finalproject.app/Contents/Resources/empty.lproj
	
finalproject.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) finalproject.app/Contents || $(MKDIR) finalproject.app/Contents 
	@$(DEL_FILE) finalproject.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,finalproject,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang/Info.plist.app >finalproject.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/finalproject1.0.0 || $(MKDIR) .tmp/finalproject1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/finalproject1.0.0/ && $(COPY_FILE) --parents account.h common.h connector.h create_account.h dialog.h entry.h favorite.h mainwindow.h movies.h result.h series.h sign_out.h whats_new.h .tmp/finalproject1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/finalproject1.0.0/ && $(COPY_FILE) --parents account.cpp common.cpp connector.cpp create_account.cpp dialog.cpp entry.cpp favorite.cpp main.cpp mainwindow.cpp movies.cpp result.cpp series.cpp sign_out.cpp whats_new.cpp .tmp/finalproject1.0.0/ && (cd `dirname .tmp/finalproject1.0.0` && $(TAR) finalproject1.0.0.tar finalproject1.0.0 && $(COMPRESS) finalproject1.0.0.tar) && $(MOVE) `dirname .tmp/finalproject1.0.0`/finalproject1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/finalproject1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r finalproject.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_account.cpp moc_create_account.cpp moc_dialog.cpp moc_entry.cpp moc_favorite.cpp moc_mainwindow.cpp moc_movies.cpp moc_result.cpp moc_series.cpp moc_sign_out.cpp moc_whats_new.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_account.cpp moc_create_account.cpp moc_dialog.cpp moc_entry.cpp moc_favorite.cpp moc_mainwindow.cpp moc_movies.cpp moc_result.cpp moc_series.cpp moc_sign_out.cpp moc_whats_new.cpp
moc_account.cpp: account.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ account.h -o moc_account.cpp

moc_create_account.cpp: create_account.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ create_account.h -o moc_create_account.cpp

moc_dialog.cpp: dialog.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ dialog.h -o moc_dialog.cpp

moc_entry.cpp: entry.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ entry.h -o moc_entry.cpp

moc_favorite.cpp: result.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		entry.h \
		favorite.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ favorite.h -o moc_favorite.cpp

moc_mainwindow.cpp: movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		whats_new.h \
		series.h \
		mainwindow.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_movies.cpp: movies.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ movies.h -o moc_movies.cpp

moc_result.cpp: result.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ result.h -o moc_result.cpp

moc_series.cpp: series.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ series.h -o moc_series.cpp

moc_sign_out.cpp: sign_out.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ sign_out.h -o moc_sign_out.cpp

moc_whats_new.cpp: result.h \
		sign_out.h \
		account.h \
		connector.h \
		common.h \
		entry.h \
		whats_new.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ whats_new.h -o moc_whats_new.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		logo2.png \
		logo.png \
		back_home.png \
		movies_logo.png \
		images/007.png \
		images/logo.png \
		images/009.png \
		images/copy.png \
		images/10.png \
		images/background.jpeg \
		images/green.jpeg \
		images/11.png \
		images/12.png \
		images/wood.png \
		images/images.jpeg \
		images/17.png
	/usr/local/Cellar/qt/4.8.4/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

account.o: account.cpp account.h \
		sign_out.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o account.o account.cpp

common.o: common.cpp common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o common.cpp

connector.o: connector.cpp connector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connector.o connector.cpp

create_account.o: create_account.cpp create_account.h \
		connector.h \
		dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		sign_out.h \
		account.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o create_account.o create_account.cpp

dialog.o: dialog.cpp dialog.h \
		create_account.h \
		common.h \
		connector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

entry.o: entry.cpp entry.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entry.o entry.cpp

favorite.o: favorite.cpp favorite.h \
		result.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o favorite.o favorite.cpp

main.o: main.cpp dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

movies.o: movies.cpp movies.h \
		favorite.h \
		result.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		entry.h \
		mainwindow.h \
		dialog.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movies.o movies.cpp

result.o: result.cpp result.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		entry.h \
		favorite.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result.o result.cpp

series.o: series.cpp series.h \
		favorite.h \
		result.h \
		connector.h \
		sign_out.h \
		account.h \
		common.h \
		entry.h \
		mainwindow.h \
		movies.h \
		dialog.h \
		whats_new.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o series.o series.cpp

sign_out.o: sign_out.cpp sign_out.h \
		dialog.h \
		mainwindow.h \
		movies.h \
		entry.h \
		result.h \
		favorite.h \
		connector.h \
		account.h \
		common.h \
		whats_new.h \
		series.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sign_out.o sign_out.cpp

whats_new.o: whats_new.cpp whats_new.h \
		result.h \
		sign_out.h \
		account.h \
		connector.h \
		common.h \
		entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whats_new.o whats_new.cpp

moc_account.o: moc_account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_account.o moc_account.cpp

moc_create_account.o: moc_create_account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_create_account.o moc_create_account.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_entry.o: moc_entry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_entry.o moc_entry.cpp

moc_favorite.o: moc_favorite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_favorite.o moc_favorite.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_movies.o: moc_movies.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_movies.o moc_movies.cpp

moc_result.o: moc_result.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_result.o moc_result.cpp

moc_series.o: moc_series.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_series.o moc_series.cpp

moc_sign_out.o: moc_sign_out.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sign_out.o moc_sign_out.cpp

moc_whats_new.o: moc_whats_new.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whats_new.o moc_whats_new.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

